// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSys.Data;

namespace SchoolSys.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20190313211918_initial create")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolSys.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassName");

                    b.Property<int>("TutorForeignKey");

                    b.HasKey("Id");

                    b.HasIndex("TutorForeignKey")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolSys.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("StudentId");

                    b.Property<int?>("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("SchoolSys.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("ChildId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MailAddress");

                    b.Property<string>("PESEL");

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("SchoolSys.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("ClassId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MailAddress");

                    b.Property<string>("PESEL");

                    b.Property<int?>("SubjectId");

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolSys.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectName");

                    b.Property<int?>("SubjectTeacherId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectTeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolSys.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MailAddress");

                    b.Property<string>("PESEL");

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolSys.Models.Class", b =>
                {
                    b.HasOne("SchoolSys.Models.Teacher", "Tutor")
                        .WithOne("Class")
                        .HasForeignKey("SchoolSys.Models.Class", "TutorForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SchoolSys.Models.Mark", b =>
                {
                    b.HasOne("SchoolSys.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId");

                    b.HasOne("SchoolSys.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("SchoolSys.Models.Parent", b =>
                {
                    b.HasOne("SchoolSys.Models.Student", "Child")
                        .WithMany("Parents")
                        .HasForeignKey("ChildId");
                });

            modelBuilder.Entity("SchoolSys.Models.Student", b =>
                {
                    b.HasOne("SchoolSys.Models.Class", "Class")
                        .WithMany("ClassMembers")
                        .HasForeignKey("ClassId");

                    b.HasOne("SchoolSys.Models.Subject")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("SchoolSys.Models.Subject", b =>
                {
                    b.HasOne("SchoolSys.Models.Teacher", "SubjectTeacher")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectTeacherId");
                });
#pragma warning restore 612, 618
        }
    }
}
